build: off

environment:
  matrix:
  - nodejs_version: "8"
  - nodejs_version: "6"
  - nodejs_version: "4"

platform:
  - x86

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm test
